---
name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive server-build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: pkg/server/dist
          retention-days: 1
      - name: Archive tree-sitter-build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-build
          path: pkg/tree-sitter
          retention-days: 1
  npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Download server-build artifacts
        uses: actions/download-artifact@v4
        with:
          name: server-build
      - name: Publish server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish -w @mistweaverco/kulala-ls
      - name: Download tree-sitter-build artifacts
        uses: actions/download-artifact@v4
        with:
          name: tree-sitter-build
      - name: Publish tree-sitter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish -w @mistweaverco/tree-sitter-kulala
  github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://npm.pkg.github.com"
      - name: Download server-build artifacts
        uses: actions/download-artifact@v4
        with:
          name: server-build
      - name: Publish server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish -w @mistweaverco/kulala-ls
      - name: Download tree-sitter-build artifacts
        uses: actions/download-artifact@v4
        with:
          name: tree-sitter-build
      - name: Publish tree-sitter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish -w @mistweaverco/tree-sitter-kulala
